### PR TITLE
renamed provider to fit current status of alternative usage in distributions / Add SLES12/15 support

### PR DESCRIPTION
**Pull request by pseiler**
#### Pull Request (PR) description
I renamed the rpm provider for this module as it fits the current distribution usage more. I also tested support for SLES12 and SLES15, which have the same functionality in ``update-alternatives`` as debian-based systems have. RHEL based system instead chkconfigs implementation.

Things I've done:
* renamed 'rpm' to 'chkconfig'
* added 'osfamily' 'Suse' as default for 'dpkg' provider
  (tested with SLES12 SP4 and SLES15 SP1)
* updated metadata.json according to new SLES support

### CODE REVIEW

**Comment by pseiler** [comment]
I'll fix the failing travis checks ;)

**Comment by pseiler** [comment]
@ekohl maybou you'll have a look. Thank you in advance!

**Comment by ekohl** [comment]
I don't really use alternatives so I feel like I'm not very qualified to review.

**Comment by pseiler** [comment]
any news regarding this pr?

**Comment by pseiler** [comment]
@ghoneycutt what would be a good solution? I have no idea.

As SUSE based systems use rpm, not dpkg imo the provider name is wrong as SUSE belongs to dpkg based system in this constellation

**Comment by pseiler** [comment]
ping

**Comment by pseiler** [comment]
ping

**Comment by pseiler** [comment]
Can this be merged or could someone provide me a hint to another solution for this. I'd like to use this code in our productive environment which contain SLES servers.

Without a change like this the puppet run on our SLES servers would fail. And maintaining a fork is also a bad idea.
@ghoneycutt @bastelfreak @ekohl

**Comment by pseiler** [comment]
ping

**Comment by ekohl** [comment]
I disagree with the naming. RPM based uses https://github.com/fedora-sysv/chkconfig which isn't an old version but really a different flavor. Fedora uses that and it's still receiving updates. In Debian it's provided by dpkg as a [util](https://salsa.debian.org/dpkg-team/dpkg/-/tree/master/utils). I don't know what the upstream for Suse is but following the naming of upstreams is probably more correct.

**Comment by pseiler** [comment]
I also researched again and got the same result. I also checked SUSE distributions and they indeed use the debian tools. 
Proof:
```bash
rpm -qpi https://download.opensuse.org/distribution/leap/15.1/repo/oss/x86_64/update-alternatives-1.19.0.4-lp151.3.67.x86_64.rpm
```
Output on a SLES machine:
FIXME add it from work machine afterwards

I now suggest following naming scheme
dpkg -> dpkg-utils
rpm  -> chkconfig

Is this okay with you @ekohl. If yes I will update this pr and mention you again?

**Comment by pseiler** [comment]
@ekohl @ghoneycutt  I just changed everything so it fit's our discussion etc. I also updated the introduction message so it won't get confusing. Please have a look and merge it, if everything is fine.

**Comment by pseiler** [comment]
The travis check was successfull. Mabye some hiccup

**Pull request merged**
